### ISSUE TITLE
PHP 8 hatası

### ISSUE THREAD

**Issue by eminozlem** [PARAMPOS/CMS-Entegrasyon#4]
Sipariş görüntüleme ekranında
https://imgur.com/a/SfVMSIw
` Fatal error: Uncaught Error: Non-static method Transaction::getTransactionByOrderId() cannot be called statically`

**Comment by gencnesil** [comment]
Güncelleme yapılarak işlem sağlanmıştır güncel eklentiyi kullanabilirsiniz, iyi çalışmalar dileriz.
