### ISSUE TITLE
"Geçersiz vergi sınıfı" hatası

### ISSUE THREAD

**Issue by denizutku35** [PARAMPOS/CMS-Entegrasyon#5]
Merhaba,

Eklentiyi ilk kez kurdum. Linkte verdiği hatayı paylaşıyorum. Bu site tarafında bir sorun mu yoksa eklenti tarafında mı? Nasıl düzeltebilirim?

https://prnt.sc/rkkFSHo-RYb7

Teşekkürler.

**Comment by gencnesil** [comment]
Merhabalar vergi sınıfı kısmına Sıfır Oran yada Zero Rate yazarak güncelleyin düzelecektir.
